grete_blog/urls.py
from django.urls import path

# import View dari grete_blog Application
from .views import index_view, detail_view, create_view, update_view, delete_view


app_name = "blog"
urlpatterns = [
    # route untuk halaman daftar blog
    path("", index_view, name="index"),
    # route untuk halaman detail blog
    path("<str:blog_slug>", detail_view, name="detail"),
    # url untuk halaman tambah blog
    path("create/", create_view, name="create"),
    # url untuk halaman ubah blog
    path("update/<str:blog_slug>", update_view, name="update"),
    # url untuk menghapus blog
    path("delete/<str:blog_slug>", delete_view, name="delete"),
]

grete_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls import handler404

handler404 = "grete_blog.views.custom_404"

urlpatterns = [
    # homepage
    path("", include("grete_blog.urls")),
    path("admin/", admin.site.urls),
    # add route from grete_blog Application
    path("blog/", include("grete_blog.urls")),
]

grete_blog/models.py
from django.db import models
from django.utils.text import slugify
from django.db.models import Model


# Create your models here.
class Blog(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True, blank=True, null=True)
    content = models.TextField()
    created_at = (models.DateTimeField(auto_now_add=True),)
    updated_at = (models.DateTimeField(auto_now=True),)

    class Meta:
        # define table name
        db_table = "grete_blog_blog"

    def save(self, *args, **kwargs):
        # Membuat slug dari judul jika belum ada
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

grete_blog/forms.py
from django.forms import ModelForm
from django.utils.translation import gettext_lazy as _

# import class Blog dari file grete_blog/models.py
from .models import Blog


# membuat class BlogForm untuk membuat Blog
class BlogForm(ModelForm):
    class Meta:
        # merelasikan form dengan model
        model = Blog
        # mengeset field apa saja yang akan ditampilkan pada form
        fields = ("title", "slug", "content")
        # mengatur teks label untuk setiap field
        labels = {
            "title": _("Judul"),
            "slug": _("Slug"),
            "content": _("Konten"),
        }
        # mengatur teks pesan error untuk setiap validasi fieldnya
        error_messages = {
            "title": {
                "required": _("Judul harus diisi."),
            },
            "content": {
                "required": _("Konten harus diisi."),
            },
        }

grete_blog/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.http import Http404
from django.contrib import messages

# import class BLog dari file grete_blog
from .models import Blog

# import class BlogForm dari file grete_blog/forms.py
from .forms import BlogForm


# Membuat View untuk halaman daftar blog
def index_view(request):
    # Mengambil semua data blog
    blogs = Blog.objects.all()
    context = {"blogs": blogs}
    # memparsing data blog ke template grete_blog/index.html dan merender nya
    return render(request, "grete_blog/index.html", context)


def detail_view(request, blog_slug):
    # Mengambil data blog berdasarkan slug
    # Fungsi GET harus spesifik gini ya
    blog = get_object_or_404(Blog, slug=blog_slug)

    context = {"blog": blog}

    # parsing data blog ke template grete_blog/detail.html dan merendernya
    return render(request, "grete_blog/detail.html", context)


def create_view(request):
    # Mengecek method pada request
    # Jika method-nya adalah POST, maka akan dijalankan
    # proses validasi dan penyimpanan data
    if request.method == "POST":
        # membuat objek dari class BlogForm
        new_blog = BlogForm(request.POST)
        # Mengecek validasi form
        if new_blog.is_valid():
            # Simpan data ke dalam table Blogs
            new_blog.save()
            # mengeset pesan sukses dan redirect ke halaman daftar blog
            messages.success(request, "Sukses Menambah Blog baru.")
            return redirect("blog:index")
        else:
            # Jika form tidak valid, kembalikan objek form ke template untuk ditampilkan
            return render(request, "grete_blog/form.html", {"form": new_blog})
    # Jika method-nya bukan POST
    else:
        # membuat objek dari class BlogForm
        form = BlogForm()
        # merender template form dengan memparsing data form
        return render(request, "grete_blog/form.html", {"form": form})


# Membuat View untuk halaman form ubah Blog
def update_view(request, blog_slug):
    try:
        # mengambil data Blog yang akan diubah berdasarkan Blog id
        # Fungsi GET harus spesifik gini ya
        blog = Blog.objects.get(slug=blog_slug)
    except Blog.DoesNotExist:
        # Jika data blog tidak ditemukan,
        # maka akan di redirect ke halaman 404 (Page not found).
        raise Http404("blog tidak ditemukan.")
    # Mengecek method pada request
    # Jika method-nya adalah POST, maka akan dijalankan
    # proses validasi dan penyimpanan data
    if request.method == "POST":
        editForm = BlogForm(request.POST, instance=blog)
        if editForm.is_valid():
            # Simpan perubahan data ke dalam table blogs
            editForm.save()
            # mengeset pesan sukses dan redirect ke halaman daftar blog
            messages.success(request, "Sukses Mengubah blog.")
            return redirect("blog:index")
        else:
            # Jika form tidak valid, kembalikan objek form ke template untuk ditampilkan
            return render(request, "grete_blog/form.html", {"form": editForm})
    # Jika method-nya bukan POST
    else:
        # membuat objek dari class BlogForm
        form = BlogForm(instance=blog)
    # merender template form dengan memparsing data form
    return render(request, "grete_blog/form.html", {"form": form})


# Membuat View untuk menghapus data Blog
def delete_view(request, blog_slug):
    try:
        # mengambil data Blog yang akan dihapus berdasarkan Blog id
        deleteBlog = Blog.objects.get(slug=blog_slug)
        # menghapus data dari table blogs
        deleteBlog.delete()
        # mengeset pesan sukses dan redirect ke halaman daftar Blog
        messages.success(request, "Sukses Menghapus Blog.")
        return redirect("blog:index")
    except Blog.DoesNotExist:
        # Jika data Blog tidak ditemukan,
        # maka akan di redirect ke halaman 404 (Page not found).
        raise Http404("Blog tidak ditemukan.")


def custom_404(request, exception):
    return render(request, "grete_blog/404.html", status=404)

grete_blog/templates/grete_blog/detail.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no" />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous" />

    <title>Blog App - Detail Blog</title>

    <style>
      body {
        margin-top: 30px;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <h1>Detail Blog</h1>

      <div>
        <a href="{% url 'blog:index' %}" class="btn btn-success"
          >Kembali ke Daftar</a
        >
      </div>

      <br />

      <div>
        <h2>{{ blog.title }}</h2>
        <h4><span class="badge badge-warning">{{ blog.slug }}</span></h4>
        <p>{{ blog.content }}</p>
      </div>
    </div>

    <!-- Optional: jQuery first, then Popper.js, then Bootstrap JS -->
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"></script>
  </body>
</html>

grete_blog/templates/grete_blog/form.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Blog App</title>

    <style>
      body {
        margin-top: 30px;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <h1>Blog Form</h1>

      <div>
        <a href="{% url 'blog:index' %}" class="btn btn-success">Back to List</a>
      </div>

      <br>

      <div>
        <!-- meload package untuk merender form field -->
        {% load widget_tweaks %}

        <form method="post" novalidate>
          <!-- menambahkan csrf field untuk keamanan form -->
          {% csrf_token %}

          <!-- merender semua field form dari objek BlogForm -->
          {% if form.non_field_errors %}
            <div class="alert alert-danger" role="alert">
              {% for error in form.non_field_errors %}
                {{ error }}
              {% endfor %}
            </div>
          {% endif %}

          {% for field in form.visible_fields %}
            <div class="form-group">
              {{ field.label_tag }}

              {% if form.is_bound %}
                {% if field.errors %}
                  {% render_field field class="form-control is-invalid" %}
                  {% for error in field.errors %}
                    <div class="invalid-feedback">
                      {{ error }}
                    </div>
                  {% endfor %}
                {% else %}
                  {% render_field field class="form-control is-valid" %}
                {% endif %}
              {% else %}
                {% render_field field class="form-control" %}
              {% endif %}

              {% if field.help_text %}
                <small class="form-text text-muted">{{ field.help_text }}</small>
              {% endif %}
            </div>
          {% endfor %}

          <button type="submit" class="btn btn-primary">Submit</button>
        </form>
      </div>
  </div>
 
  </body>
</html>

grete_blog/templates/grete_blog/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no" />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous" />

    <title>Grete &mdash; Blog</title>

    <style>
      body {
        margin-top: 30px;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <h1>Daftar blog</h1>

      <!-- blok untuk menampilkan notifikasi pesan sukses -->
      <div>
        {% if messages %} {% for message in messages %}

        <div
          class="alert alert-{{ message.tags }} alert-dismissible fade show"
          role="alert">
          <button
            type="button"
            class="close"
            data-dismiss="alert"
            aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>

          {{ message | safe }}
        </div>

        {% endfor %} {% endif %}
      </div>

      <!-- tombol untuk ke halaman tambah blog -->
      <div>
        <a href="{% url 'blog:create'  %}" class="btn btn-success"
          >Tambah Baru</a
        >
      </div>

      <br />

      <table class="table table-bordered table-striped">
        <thead>
          <tr>
            <th width="5%">ID</th>
            <th width="20%">Judul</th>
            <th width="45%">Slug</th>
            <th width="5%">content</th>
            <th width="20%">Aksi</th>
          </tr>
        </thead>
        <tbody>
          <!-- daftar blog-->
          {% if blogs %} {% for blog in blogs %}
          <tr>
            <td>{{ blog.id }}</td>
            <td>{{ blog.title }}</td>
            <td>{{ blog.slug }}</td>
            <td>{{ blog.content }}</td>
            <td>
              <a
                href="{% url 'blog:detail' blog.slug %}"
                class="btn btn-warning btn-sm"
                >detail</a
              >
              <a
                href="{% url 'blog:update' blog.slug %}"
                class="btn btn-primary btn-sm"
                >ubah</a
              >
              <a
                href="{% url 'blog:delete' blog.slug %}"
                class="btn btn-danger btn-sm"
                onclick="return confirm('Apakah yakin akan menghapus blog ini?')"
                >hapus</a
              >
            </td>
          </tr>
          {% endfor %} {% else %}
          <tr>
            <td colspan="5">Data tidak ditemukan.</td>
          </tr>
          {% endif %}
        </tbody>
      </table>
    </div>
  </body>
</html>